# Generated by Django 3.0.7 on 2020-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEmail',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login_email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginPermissions',
            fields=[
                ('user_role', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('show_site', models.IntegerField()),
                ('show_irt_statistics', models.IntegerField(db_column='show_IRT_statistics')),
                ('show_history_statistics', models.IntegerField()),
                ('show_silos_err', models.IntegerField(db_column='show_silos_ERR')),
                ('show_resolve_errr', models.IntegerField(db_column='show_resolve_ERRR')),
            ],
            options={
                'db_table': 'login_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'login_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilosAvgDay',
            fields=[
                ('silos_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('data_day', models.FloatField()),
            ],
            options={
                'db_table': 'silos_avg_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilosAvgMonth',
            fields=[
                ('silos_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('data_month', models.FloatField()),
            ],
            options={
                'db_table': 'silos_avg_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilosAvgWeek',
            fields=[
                ('silos_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('data_week', models.FloatField()),
            ],
            options={
                'db_table': 'silos_avg_week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilosData',
            fields=[
                ('user_role', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('show_site', models.IntegerField()),
                ('show_irt_statistics', models.IntegerField(db_column='show_IRT_statistics')),
                ('show_history_statistics', models.IntegerField()),
                ('show_silos_err', models.IntegerField(db_column='show_silos_ERR')),
                ('show_resolve_err', models.IntegerField(db_column='show_resolve_ERR')),
            ],
            options={
                'db_table': 'silos_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilosDataIrt',
            fields=[
                ('silos_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('silos_data_time', models.DateField()),
                ('silos_value', models.FloatField()),
                ('error_code', models.TextField()),
            ],
            options={
                'db_table': 'silos_data_irt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilosError',
            fields=[
                ('error_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('error_description', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'silos_error',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SilosErrorCategory',
            fields=[
                ('error_code', models.AutoField(primary_key=True, serialize=False)),
                ('error_description', models.CharField(max_length=3)),
                ('silos_code', models.CharField(max_length=12)),
                ('error_data_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'silos_error_category',
                'managed': False,
            },
        ),
    ]
